apiVersion: neuronetes.io/v1alpha1
kind: Model
metadata:
  name: llama-3-70b-rag
  namespace: rag-system
spec:
  weightsURI: s3://models/llama-3-70b-instruct/
  size: 140Gi
  quantization: int4
  architecture: llama
  parameterCount: "70B"
  shardSpec:
    count: 4
    strategy: tensor-parallel
    topology:
      locality: same-node
  cachePolicy:
    priority: high
    pinDuration: 4h
---
apiVersion: neuronetes.io/v1alpha1
kind: Model
metadata:
  name: embedding-model
  namespace: rag-system
spec:
  weightsURI: s3://models/bge-large-en-v1.5/
  size: 1.3Gi
  quantization: fp16
  architecture: bert
  format: safetensors
  cachePolicy:
    priority: critical
    pinDuration: 24h
    evictionPolicy: never
