apiVersion: neuronetes.io/v1alpha1
kind: Model
metadata:
  name: llama-3-8b-chat
  namespace: default
spec:
  weightsURI: s3://models/llama-3-8b-instruct/
  size: 16Gi
  quantization: int8
  architecture: llama
  parameterCount: "8B"
  format: safetensors
  cachePolicy:
    priority: medium
    pinDuration: 1h
    evictionPolicy: lru
